
# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android
trigger:
- main

pool: Default

steps:
- task: CmdLine@2
  inputs:
    script: 'curl -u "emmamalysz_4PgZUS:BRKYBgoRtwernJha1Pjk" -X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/build" -d ''{"app": "bs://2e5b8d9a7ffaf84912ce3e62406864d1b5bbfe65", "testSuite": "bs://dbd9b6b84dc357804e33f7d1b00f28ebd75309b9", "devices": ["Samsung Galaxy S9 Plus-9.0"]}'' -H "Content-Type: application/json"'
      






